name: e_menu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Locale
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Navigation
  octopus: ^0.0.9

  # Data
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

  # UI
  cupertino_icons: ^1.0.8
  
  # Utility
  platform_info: ^5.0.0
  talker_flutter: ^4.7.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.15
  pubspec_generator: ^4.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
